baseURL = "http://andrewshmann.com/"
languageCode = "ru"
disqusShortname = "koroandr"
title = "Бложик Андрюшмана"
theme = "pickles"
author = "Андрей Королёв"
disqus = "koroandr"
[params]
  ga_api_key = "UA-108831994-1"
